version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - database
      - php
    ports:
      - "8080:80"
    networks:
      - api

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      TZ: Europe/Prague
    volumes:
      - ./:/var/www/html/
    depends_on:
      - database
    networks:
      - api

  adminer:
    image: dockette/adminer:dg
    restart: always
    depends_on:
      - database
    ports:
      - "8000:80"
    networks:
      - api

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      TZ: Europe/Prague
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api

networks:
  api:

volumes:
  db_data: