version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - database
      - php
    ports:
      - "8080:80"
    networks:
      - api

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/
    depends_on:
      - database
    networks:
      - api

  database:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: api_platform
      MARIADB_USER: user
      MARIADB_PASSWORD: userpass
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api

networks:
  api:

volumes:
  db_data: